spring:
  influxdb2:
    url: http://10.10.0.230:8086
    bucket: jetlinks
    org: zz
    token: ojSXPe0IKeV1mGnQBMBDIjAeQiRBQZiwTPGPuGY8-b13ZXdd3SDFbi0G4qtrkYF_DVcRpPGtazURH8taXXhsGQ==
  resources:
    static-locations: file:./index/, file:./static/,/,classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/, classpath:/public/
  redis:
    host: 10.10.0.230
    port: 9736
    lettuce:
      pool:
        max-active: 1024
    timeout: 20s
    password:
    database: 1
  r2dbc:
    url: r2dbc:h2:file:///./data/h2db/jetlinks
    username: sa
    password:
    pool:
      max-size: 32
  data:
    elasticsearch:
      client:
        reactive:
          endpoints: ${elasticsearch.client.host}:${elasticsearch.client.port}
          max-in-memory-size: 100MB
          socket-timeout: ${elasticsearch.client.socket-timeout}
          connection-timeout: ${elasticsearch.client.socket-timeout}
easyorm:
  default-schema: PUBLIC # 数据库默认的schema
  dialect: h2 #数据库方言
elasticsearch:
  embedded:
    enabled: true # 为true时使用内嵌的elasticsearch,不建议在生产环境中使用
    data-path: ./data/elasticsearch
    port: 9201
    host: 0.0.0.0
  client:
    host: localhost
    port: 9201
    max-conn-total: 128
    connect-timeout: 5000
    socket-timeout: 5000
    connection-request-timeout: 8000
  index:
    default-strategy: time-by-month #默认es的索引按月进行分表, direct则为直接操作索引.
    settings:
      number-of-shards: 1 # es 分片数量
      number-of-replicas: 0 # 副本数量
device:
  message:
    writer:
      time-series:
        enabled: true #写出设备消息数据到elasticsearch
logging:
  level:
    com.github.tonivade: error
jetlinks:
  device:
    storage:
      default-policy: influxdb2-column